### ISSUE TITLE
Automatically add 'nofollow' to all links

### ISSUE THREAD

**Issue by fisharebest** [IET-OU/cloudengine#339]
Due to occasional spam, add nofollow to all links on the sites, in particular those on prfiles. 

---
- Bitbucket: https://bitbucket.org/cloudengine/cloudengine/issue/339
- Originally Reported By: [Juliette Culver](http://bitbucket.org/julietteculver)
- Originally Created At: 2013-03-08T14:59:48.123

**Comment by nfreear** [comment]
* Duplicate of: #364.

Closing,

N.
